version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - social_gallery

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: $MYSQL_HOST
      PMA_PORT: $MYSQL_PORT
      PMA_USER: $MYSQL_USER
      PMA_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - social_gallery

  server:
    build: ./server/
    ports:
      - "3001:3001"
    volumes:
      - ./server:/server
      - server_node_modules:/server/node_modules
    depends_on:
      - db
    networks:
      - social_gallery
    stdin_open: true
    tty: true

  client:
    build: ./client/
    ports:
      - "8000:8000"
    depends_on:
      - server
    volumes:
      - ./client:/client
      - client_node_modules:/client/node_modules
    networks:
      - social_gallery
    tty: true

networks:
  social_gallery:
    driver: bridge

volumes:
  db:
  server_node_modules:
  client_node_modules:
